### PR TITLE
Add wolfram sponsor track

### PR DESCRIPTION
**Pull request by AkashPaloju**
Adds Wolfram track prize

### CODE REVIEW

**Comment by AkashPaloju** [comment]
@mittalvansh PTAL

**Comment by mittalvansh** [comment]
@AkashPaloju 
The image for Wolfram doesn't look good; also, please set the width and height for the image on the card, as they are currently uneven.

**Comment by AkashPaloju** [comment]
is this ok 
wolfram

**Comment by mittalvansh** [comment]
No, the previous logo was fine, just add white space around it, similar to the other logos, and define the image's width and height for the card. This will ensure it looks good on all views.

**Comment by mittalvansh** [comment]
If you encounter any issues with obtaining the correct logo, please reach out to Adi for assistance.

**Comment by mittalvansh** [comment]
Screenshot from 2024-03-28 01-52-45

Here, you can see images are uneven, solve this thing @AkashPaloju

**Comment by AkashPaloju** [comment]
> Screenshot from 2024-03-28 01-52-45
> 
> Here, you can see images are uneven, solve this thing @AkashPaloju

just check in  hackbyte.in

**Comment by AkashPaloju** [comment]
@mittalvansh pls check the image now, is it ok, else I will ask Adi Sir (couldn't pad the previous one)

**Comment by mittalvansh** [comment]
ask adi to pad the previous one

**Comment by mittalvansh** [comment]
image

Also, view for larger screens doesn't look good, fix that, you can set a larger width and height for larger screens.

**Comment by AkashPaloju** [comment]
@mittalvansh fixed image to fit PTAL. aAlso added padding for image now, if it is fine merge it , else we will wait till Adi sir send that image.

**Comment by AkashPaloju** [comment]
@mittalvansh PTAL, For now Added some relevant text in partners page

**Comment by mittalvansh** [comment]
@AkashPaloju 
LGTM, Can you please modify the Logitech card in the partners page according to the design?
Refer Figma for this.

**Comment by mittalvansh** [comment]
Try to do this asap, Logitech has given 1hr deadline for this.

**Comment by AkashPaloju** [comment]
@mittalvansh , Please merge till this, now I have to go to Railway station

**Pull request merged**
