### PR TITLE
refactor:Remove home in navbar , add logo

### PR DESCRIPTION
**Pull request by AkashPaloju**
This PR does the following tasks:
- Removes the 'home' item from the navbar in desktop, mobile view.
- Adds a logo that serves as a link ('href') to the 'home' route in desktop, mobile view

### CODE REVIEW

**Comment by AkashPaloju** [comment]
@mittalvansh  PTAL.

**Review by mittalvansh — CHANGES_REQUESTED** [review]
@AkashPaloju , please ensure that the logo is clickable on mobile view as well. No separate option for the home is required. Additionally, refrain from duplicating the image; instead, implement the necessary changes directly within the existing logo.

**Comment by AkashPaloju** [comment]
@mittalvansh PTAL

**Comment by mittalvansh** [comment]
@AkashPaloju 
The changes are cool, but at 1024 screen size, things look off. Let's just hold off a bit; we need to trim down the navbar size even more. We're considering combining the home and about pages, so let's wait for the design before merging these tweaks.

**Comment by mittalvansh** [comment]
@AkashPaloju please resolve your conflicts.

**Comment by AkashPaloju** [comment]
resolved conflicts, @mittalvansh PTAL

**Pull request merged**
